[package]
name = "lockness-vecs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "TODO"
repository.workspace = true
keywords = ["mpmc", "mpsc", "lock-free", "parallel", "performance"]
categories = ["concurrency", "asynchronous", "data-structures"]
license.workspace = true

[dev-dependencies]
criterion = "0.5.1"
proptest = "1.2.0"
proptest-derive = "0.4.0"
supercilex-tests = "0.3.4"

[[bench]]
name = "closure_vec"
harness = false
