[package]
name = "lockness-vecs"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "TODO"
repository.workspace = true
keywords = ["mpmc", "mpsc", "lock-free", "parallel", "performance"]
categories = ["concurrency", "asynchronous", "data-structures"]
license.workspace = true

[dev-dependencies]
criterion = "0.6.0"
proptest = "1.7.0"
proptest-derive = "0.6.0"
supercilex-tests = { version = "0.4.18", default-features = false, features = ["api"] }

[[bench]]
name = "closure_vec"
harness = false
