[package]
name = "lockness-executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "TODO"
repository.workspace = true
keywords = ["executor", "blocking", "thread", "parallel", "performance"]
categories = ["concurrency", "asynchronous", "data-structures"]
license.workspace = true

[dependencies]
bon = "3.6.4"

[dev-dependencies]
criterion = "0.6.0"
flume = "0.11.1"
rayon = "1.10.0"
supercilex-tests = { version = "0.4.18", default-features = false, features = ["api"] }
tokio = "1.45.1"
