[package]
name = "lockness-executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "TODO"
repository.workspace = true
keywords = ["executor", "blocking", "thread", "parallel", "performance"]
categories = ["concurrency", "asynchronous", "data-structures"]
license.workspace = true

[dev-dependencies]
criterion = "0.5.1"
flume = "0.11.0"
rayon = "1.8.0"
supercilex-tests = { version = "0.4.13", default-features = false, features = ["api"] }
tokio = "1.35.0"
