[package]
name = "lockness-bags"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "TODO"
repository.workspace = true
keywords = ["mpmc", "mpsc", "lock-free", "parallel", "performance"]
categories = ["concurrency", "asynchronous", "data-structures"]
license.workspace = true

[dependencies]
arrayvec = "0.7.6"
bitflags = "2.9.1"
rustix = { version = "1.0.7", features = ["thread", "linux_latest"] }

[dev-dependencies]
async-channel = "2.3.1"
concurrent-queue = "2.5.0"
criterion = "0.6.0"
crossbeam-channel = "0.5.15"
crossbeam-deque = "0.8.6"
crossbeam-queue = "0.3.12"
flume = "0.11.1"
ringbuf = "0.4.8"
rstest = "0.25.0"
supercilex-tests = "0.4.18"
thingbuf = "0.1.6"

#[[bench]]
#name = "atomic_bag"
#harness = false
